[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:php]
command=%(ENV_SUPERVISOR_PHP_COMMAND)s
user=%(ENV_SUPERVISOR_PHP_USER)s
environment=LARAVEL_SAIL="1",DB_HOST="%(ENV_DB_HOST)s",REDIS_HOST="%(ENV_REDIS_HOST)s",MAIL_HOST="%(ENV_MAIL_HOST)s",MAIL_MAILER="%(ENV_MAIL_MAILER)s",MAIL_PORT="%(ENV_MAIL_PORT)s"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
